### ISSUE TITLE
Default Passphrase?

### ISSUE THREAD

**Issue by aea434** [ubports-on-vince/ubports-ci#3]
I got the OS successfully running but it's passphrase locked. What's the default passphrase? I tried "phablet" but it doesn't work.

**Comment by 0312birdzhang** [comment]
Default password is `1234`.
https://github.com/ubports-on-vince/ubports-ci/blob/d3d4268eaadac266d814303188867f9111f49191/META-INF/com/google/android/updater-script#L31

**Comment by aea434** [comment]
Thanks, you're the best!
