### ISSUE TITLE
Rotation is possibly broken on v1.0.5 release

### ISSUE THREAD

**Issue by ncyxie** [ubports-on-vince/ubports-ci#5]
**Rotation possibly broken on v1.0.5 release.**

**Rotation lock is disabled.** Tried to rotate device in many ways as possible to landscape mode, it is still always on portrait mode.

**Comment by 0312birdzhang** [comment]
Confirmed, will try to fix it this weekend.

**Comment by ncyxie** [comment]
Rotation bug fixed on **'Release v1.1.1'**.
